Import-Module PowerUpJsonFallback

Set-StrictMode -Version 2.0
$ErrorActionPreference = "Stop"

Describe 'ConvertTo-Json' {
    It 'should convert PS Hashtable' {
        $result = ConvertTo-Json @{a="b"}
        $result | Should Be '{"a":"b"}'
    }

    It 'should convert PS Array' {
        $result = ConvertTo-Json @(1,2,3)
        $result | Should Be '[1,2,3]'
    }
    
    It 'should convert PS Array generated by ForEach-Object' {
        Add-Type -TypeDefinition "using System.Collections;
        
        public static class Reflect {
            public static string GetKeys(object value) {
                var result = `"`";
                foreach (var key in ((Hashtable)value).Keys) {
                    result += key + `",`";
                }
                return result;
            }
        }"
    
        $data = @(@(1,2,3) | % { @{x=$_} })
        $result = ConvertTo-Json @(@(1,2,3) | % { @{x=$_} })
        $result | Should Be '[{"x":1},{"x":2},{"x":3}]'
    }
    
    It 'should escape slashes in strings' {
        $result = ConvertTo-Json "a\b"
        $result | Should Be '"a\\b"'
    }
        
    It 'should return string' {
        $result = ConvertTo-Json @{
            property1 = 'value1'
            property2 = 2
        }
        $result.GetType() | Should Be string
    }
}